'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd"),  _
 System.Xml.Serialization.XmlRootAttribute("policeGisConfig", [Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd", IsNullable:=false)>  _
Partial Public Class PoliceGisConfiguration
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private releaseField As ApplicationVersion
    
    Private clientField As String
    
    Private releaseDateField As Date
    
    Private directoriesField As DirectorySettings
    
    Private geocodingField As GeocodingSettings
    
    Private analysisField As AnalysisSettings
    
    Private schemaVersionField As String
    
    '''<remarks/>
    Public Property release() As ApplicationVersion
        Get
            Return Me.releaseField
        End Get
        Set
            Me.releaseField = value
            Me.RaisePropertyChanged("release")
        End Set
    End Property
    
    '''<remarks/>
    Public Property client() As String
        Get
            Return Me.clientField
        End Get
        Set
            Me.clientField = value
            Me.RaisePropertyChanged("client")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property releaseDate() As Date
        Get
            Return Me.releaseDateField
        End Get
        Set
            Me.releaseDateField = value
            Me.RaisePropertyChanged("releaseDate")
        End Set
    End Property
    
    '''<remarks/>
    Public Property directories() As DirectorySettings
        Get
            Return Me.directoriesField
        End Get
        Set
            Me.directoriesField = value
            Me.RaisePropertyChanged("directories")
        End Set
    End Property
    
    '''<remarks/>
    Public Property geocoding() As GeocodingSettings
        Get
            Return Me.geocodingField
        End Get
        Set
            Me.geocodingField = value
            Me.RaisePropertyChanged("geocoding")
        End Set
    End Property
    
    '''<remarks/>
    Public Property analysis() As AnalysisSettings
        Get
            Return Me.analysisField
        End Get
        Set
            Me.analysisField = value
            Me.RaisePropertyChanged("analysis")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property schemaVersion() As String
        Get
            Return Me.schemaVersionField
        End Get
        Set
            Me.schemaVersionField = value
            Me.RaisePropertyChanged("schemaVersion")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class ApplicationVersion
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private majorVersionField As Integer
    
    Private minorVersionField As Integer
    
    Private implementationVersionField As Integer
    
    Private buildNumberField As Integer
    
    Private buildNumberFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property majorVersion() As Integer
        Get
            Return Me.majorVersionField
        End Get
        Set
            Me.majorVersionField = value
            Me.RaisePropertyChanged("majorVersion")
        End Set
    End Property
    
    '''<remarks/>
    Public Property minorVersion() As Integer
        Get
            Return Me.minorVersionField
        End Get
        Set
            Me.minorVersionField = value
            Me.RaisePropertyChanged("minorVersion")
        End Set
    End Property
    
    '''<remarks/>
    Public Property implementationVersion() As Integer
        Get
            Return Me.implementationVersionField
        End Get
        Set
            Me.implementationVersionField = value
            Me.RaisePropertyChanged("implementationVersion")
        End Set
    End Property
    
    '''<remarks/>
    Public Property buildNumber() As Integer
        Get
            Return Me.buildNumberField
        End Get
        Set
            Me.buildNumberField = value
            Me.RaisePropertyChanged("buildNumber")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property buildNumberSpecified() As Boolean
        Get
            Return Me.buildNumberFieldSpecified
        End Get
        Set
            Me.buildNumberFieldSpecified = value
            Me.RaisePropertyChanged("buildNumberSpecified")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class AnalysisSettings
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private areasField As AnalysisSettingsAreas
    
    Private aggregationLevelsField() As String
    
    Private workspacesField As AnalysisSettingsWorkspaces
    
    Private geocodingTableField As TableSpecification
    
    '''<remarks/>
    Public Property areas() As AnalysisSettingsAreas
        Get
            Return Me.areasField
        End Get
        Set
            Me.areasField = value
            Me.RaisePropertyChanged("areas")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("AggregationLevels")>  _
    Public Property AggregationLevels() As String()
        Get
            Return Me.aggregationLevelsField
        End Get
        Set
            Me.aggregationLevelsField = value
            Me.RaisePropertyChanged("AggregationLevels")
        End Set
    End Property
    
    '''<remarks/>
    Public Property workspaces() As AnalysisSettingsWorkspaces
        Get
            Return Me.workspacesField
        End Get
        Set
            Me.workspacesField = value
            Me.RaisePropertyChanged("workspaces")
        End Set
    End Property
    
    '''<remarks/>
    Public Property geocodingTable() As TableSpecification
        Get
            Return Me.geocodingTableField
        End Get
        Set
            Me.geocodingTableField = value
            Me.RaisePropertyChanged("geocodingTable")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class AnalysisSettingsAreas
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private areaNameField As String
    
    '''<remarks/>
    Public Property areaName() As String
        Get
            Return Me.areaNameField
        End Get
        Set
            Me.areaNameField = value
            Me.RaisePropertyChanged("areaName")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class AnalysisSettingsWorkspaces
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private areaField As String
    
    Private analysisField As String
    
    Private workspaceFileField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="IDREF")>  _
    Public Property area() As String
        Get
            Return Me.areaField
        End Get
        Set
            Me.areaField = value
            Me.RaisePropertyChanged("area")
        End Set
    End Property
    
    '''<remarks/>
    Public Property analysis() As String
        Get
            Return Me.analysisField
        End Get
        Set
            Me.analysisField = value
            Me.RaisePropertyChanged("analysis")
        End Set
    End Property
    
    '''<remarks/>
    Public Property workspaceFile() As String
        Get
            Return Me.workspaceFileField
        End Get
        Set
            Me.workspaceFileField = value
            Me.RaisePropertyChanged("workspaceFile")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class TableSpecification
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private tabFileField As String
    
    Private mustExistField As Boolean
    
    Private knownColumnsField() As ColumnSpecification
    
    '''<remarks/>
    Public Property tabFile() As String
        Get
            Return Me.tabFileField
        End Get
        Set
            Me.tabFileField = value
            Me.RaisePropertyChanged("tabFile")
        End Set
    End Property
    
    '''<remarks/>
    Public Property mustExist() As Boolean
        Get
            Return Me.mustExistField
        End Get
        Set
            Me.mustExistField = value
            Me.RaisePropertyChanged("mustExist")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("column", IsNullable:=false)>  _
    Public Property knownColumns() As ColumnSpecification()
        Get
            Return Me.knownColumnsField
        End Get
        Set
            Me.knownColumnsField = value
            Me.RaisePropertyChanged("knownColumns")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class ColumnSpecification
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private roleField As String
    
    Private nameField() As String
    
    '''<remarks/>
    Public Property role() As String
        Get
            Return Me.roleField
        End Get
        Set
            Me.roleField = value
            Me.RaisePropertyChanged("role")
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("name")>  _
    Public Property name() As String()
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
            Me.RaisePropertyChanged("name")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class GeocodingSettings
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private tablesField As GeocodingSettingsTables
    
    Private maximumStreetLengthField As UInteger
    
    Private workSpaceField As String
    
    Private outputCoordinateSystemField As String
    
    Public Sub New()
        MyBase.New
        Me.maximumStreetLengthField = CType(200,UInteger)
    End Sub
    
    '''<remarks/>
    Public Property tables() As GeocodingSettingsTables
        Get
            Return Me.tablesField
        End Get
        Set
            Me.tablesField = value
            Me.RaisePropertyChanged("tables")
        End Set
    End Property
    
    '''<remarks/>
    <System.ComponentModel.DefaultValueAttribute(GetType(UInteger), "200")>  _
    Public Property MaximumStreetLength() As UInteger
        Get
            Return Me.maximumStreetLengthField
        End Get
        Set
            Me.maximumStreetLengthField = value
            Me.RaisePropertyChanged("MaximumStreetLength")
        End Set
    End Property
    
    '''<remarks/>
    Public Property workSpace() As String
        Get
            Return Me.workSpaceField
        End Get
        Set
            Me.workSpaceField = value
            Me.RaisePropertyChanged("workSpace")
        End Set
    End Property
    
    '''<remarks/>
    Public Property outputCoordinateSystem() As String
        Get
            Return Me.outputCoordinateSystemField
        End Get
        Set
            Me.outputCoordinateSystemField = value
            Me.RaisePropertyChanged("outputCoordinateSystem")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class GeocodingSettingsTables
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private geocodingStreetsField As TableSpecification
    
    Private streetLengthField As TableSpecification
    
    Private administrativeBordersField As TableSpecification
    
    Private addressPointsField As TableSpecification
    
    Private hectoMeterPolesField As TableSpecification
    
    Private addressNotFoundSelectionField As String
    
    '''<remarks/>
    Public Property geocodingStreets() As TableSpecification
        Get
            Return Me.geocodingStreetsField
        End Get
        Set
            Me.geocodingStreetsField = value
            Me.RaisePropertyChanged("geocodingStreets")
        End Set
    End Property
    
    '''<remarks/>
    Public Property streetLength() As TableSpecification
        Get
            Return Me.streetLengthField
        End Get
        Set
            Me.streetLengthField = value
            Me.RaisePropertyChanged("streetLength")
        End Set
    End Property
    
    '''<remarks/>
    Public Property administrativeBorders() As TableSpecification
        Get
            Return Me.administrativeBordersField
        End Get
        Set
            Me.administrativeBordersField = value
            Me.RaisePropertyChanged("administrativeBorders")
        End Set
    End Property
    
    '''<remarks/>
    Public Property addressPoints() As TableSpecification
        Get
            Return Me.addressPointsField
        End Get
        Set
            Me.addressPointsField = value
            Me.RaisePropertyChanged("addressPoints")
        End Set
    End Property
    
    '''<remarks/>
    Public Property hectoMeterPoles() As TableSpecification
        Get
            Return Me.hectoMeterPolesField
        End Get
        Set
            Me.hectoMeterPolesField = value
            Me.RaisePropertyChanged("hectoMeterPoles")
        End Set
    End Property
    
    '''<remarks/>
    Public Property addressNotFoundSelection() As String
        Get
            Return Me.addressNotFoundSelectionField
        End Get
        Set
            Me.addressNotFoundSelectionField = value
            Me.RaisePropertyChanged("addressNotFoundSelection")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.gim.be/PoliceGIS/PoliceGisConfiguration.xsd")>  _
Partial Public Class DirectorySettings
    Inherits Object
    Implements System.ComponentModel.INotifyPropertyChanged
    
    Private dataFolderField As String
    
    Private islpFolderField As String
    
    Private outputFolderField As String
    
    Private workFolderField As String
    
    Private exportFolderField As String
    
    '''<remarks/>
    Public Property dataFolder() As String
        Get
            Return Me.dataFolderField
        End Get
        Set
            Me.dataFolderField = value
            Me.RaisePropertyChanged("dataFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property islpFolder() As String
        Get
            Return Me.islpFolderField
        End Get
        Set
            Me.islpFolderField = value
            Me.RaisePropertyChanged("islpFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property outputFolder() As String
        Get
            Return Me.outputFolderField
        End Get
        Set
            Me.outputFolderField = value
            Me.RaisePropertyChanged("outputFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property workFolder() As String
        Get
            Return Me.workFolderField
        End Get
        Set
            Me.workFolderField = value
            Me.RaisePropertyChanged("workFolder")
        End Set
    End Property
    
    '''<remarks/>
    Public Property exportFolder() As String
        Get
            Return Me.exportFolderField
        End Get
        Set
            Me.exportFolderField = value
            Me.RaisePropertyChanged("exportFolder")
        End Set
    End Property
    
    Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
    
    Protected Sub RaisePropertyChanged(ByVal propertyName As String)
        Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
        If (Not (propertyChanged) Is Nothing) Then
            propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
        End If
    End Sub
End Class
