'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gim.PoliceGis.Core.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Add16x16_pngYellowMedium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add16x16_pngYellowMedium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Add16x16GreenLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add16x16GreenLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Analyse per gebied.
        '''</summary>
        Friend ReadOnly Property AnalyseByArea() As String
            Get
                Return ResourceManager.GetString("AnalyseByArea", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Puntanalyse.
        '''</summary>
        Friend ReadOnly Property AnalyseByPoint() As String
            Get
                Return ResourceManager.GetString("AnalyseByPoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Zwarte punten analyse.
        '''</summary>
        Friend ReadOnly Property BlackPointAnlysis() As String
            Get
                Return ResourceManager.GetString("BlackPointAnlysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à GEWIJZIGD.
        '''</summary>
        Friend ReadOnly Property Changed() As String
            Get
                Return ResourceManager.GetString("Changed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Serie inbraken.
        '''</summary>
        Friend ReadOnly Property CrimeSeries() As String
            Get
                Return ResourceManager.GetString("CrimeSeries", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Criminaliteit.
        '''</summary>
        Friend ReadOnly Property CriminalType() As String
            Get
                Return ResourceManager.GetString("CriminalType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DataContainer_MoveFirstHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveFirstHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DataContainer_MoveLastHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveLastHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DataContainer_MoveNextHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DataContainer_MovePreviousHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_MovePreviousHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DataContainer_NewRecordHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DataContainer_NewRecordHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Er is een default configuratie bestand aangemaakt.
        '''</summary>
        Friend ReadOnly Property defaultConfgurationFIleCreated() As String
            Get
                Return ResourceManager.GetString("defaultConfgurationFIleCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à NaamSpatie.
        '''</summary>
        Friend ReadOnly Property DisplayMember() As String
            Get
                Return ResourceManager.GetString("DisplayMember", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vul eerst de criteria van de selectie in, a.u.b..
        '''</summary>
        Friend ReadOnly Property ErrorCriteriaMsg() As String
            Get
                Return ResourceManager.GetString("ErrorCriteriaMsg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Tabel {0} bevat geen ruimtelijke elementen..
        '''</summary>
        Friend ReadOnly Property ErrorNoSpatialTable() As String
            Get
                Return ResourceManager.GetString("ErrorNoSpatialTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen geldige tabelnaam.
        '''</summary>
        Friend ReadOnly Property ErrorNoValidTableName() As String
            Get
                Return ResourceManager.GetString("ErrorNoValidTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à GEVONDEN.
        '''</summary>
        Friend ReadOnly Property Found() As String
            Get
                Return ResourceManager.GetString("Found", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  GIM - PolitieGIS.
        '''</summary>
        Friend ReadOnly Property GIMPoliceGis() As String
            Get
                Return ResourceManager.GetString("GIMPoliceGis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Groep veld bestaat al.
        '''</summary>
        Friend ReadOnly Property GroupFieldExist() As String
            Get
                Return ResourceManager.GetString("GroupFieldExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Legende.
        '''</summary>
        Friend ReadOnly Property Legend() As String
            Get
                Return ResourceManager.GetString("Legend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_police() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_police", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_police_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_police_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_police_square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_police_square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo_police_square_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_police_square_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à .
        '''</summary>
        Friend ReadOnly Property MapsFolder() As String
            Get
                Return ResourceManager.GetString("MapsFolder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 200.
        '''</summary>
        Friend ReadOnly Property MaxStreetDefault() As String
            Get
                Return ResourceManager.GetString("MaxStreetDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen incidenten in selectie teruggevonden.
        '''</summary>
        Friend ReadOnly Property NoIncidentsFound() As String
            Get
                Return ResourceManager.GetString("NoIncidentsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen series gevonden.
        '''</summary>
        Friend ReadOnly Property NoSerieFound() As String
            Get
                Return ResourceManager.GetString("NoSerieFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à NIET GEVONDEN.
        '''</summary>
        Friend ReadOnly Property NotFound() As String
            Get
                Return ResourceManager.GetString("NotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à extentie niet ondersteund: {0}.
        '''</summary>
        Friend ReadOnly Property NotSupportedFileExtension() As String
            Get
                Return ResourceManager.GetString("NotSupportedFileExtension", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Aantal incidenten.
        '''</summary>
        Friend ReadOnly Property NumberOfincidenten() As String
            Get
                Return ResourceManager.GetString("NumberOfincidenten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property openfolderHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("openfolderHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property PolitieGIS_desktop_32x32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PolitieGIS_desktop_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        '''</summary>
        Friend ReadOnly Property PolitieGIS_favicon_16x16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PolitieGIS_favicon_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à  het geselecteerde gebied.
        '''</summary>
        Friend ReadOnly Property SelectedZone() As String
            Get
                Return ResourceManager.GetString("SelectedZone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Selectie opgeslagen in {0}.
        '''</summary>
        Friend ReadOnly Property SelectionSavedIn() As String
            Get
                Return ResourceManager.GetString("SelectionSavedIn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Straten analyse.
        '''</summary>
        Friend ReadOnly Property StreetAnalysis() As String
            Get
                Return ResourceManager.GetString("StreetAnalysis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Deze lijst bevat de waarden die u heeft geselecteerd.
        '''</summary>
        Friend ReadOnly Property TooltipSelectedValues() As String
            Get
                Return ResourceManager.GetString("TooltipSelectedValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Uit deze waarden kunt u selecteren.
        '''</summary>
        Friend ReadOnly Property TooltipSelectValues() As String
            Get
                Return ResourceManager.GetString("TooltipSelectValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Welke waarden tot welke groep behoren.
        '''</summary>
        Friend ReadOnly Property TooltipWichValues() As String
            Get
                Return ResourceManager.GetString("TooltipWichValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Verkeer.
        '''</summary>
        Friend ReadOnly Property TrafficType() As String
            Get
                Return ResourceManager.GetString("TrafficType", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
