'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ExceptionMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gim.PoliceGis.Core.ExceptionMessages", GetType(ExceptionMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Een lege String is geen geldige waarde voor method argument &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property ArgumentIsEmptyString() As String
            Get
                Return ResourceManager.GetString("ArgumentIsEmptyString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Een null reference is geen geldige waarde voor method argument &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property ArgumentNull() As String
            Get
                Return ResourceManager.GetString("ArgumentNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Het verkeerde venster is momenteel geselecteerd. Activeer eerst weer het venster met de zwarte punten kaart, a.u.b..
        '''</summary>
        Friend Shared ReadOnly Property BlackPointWindowNotSelected() As String
            Get
                Return ResourceManager.GetString("BlackPointWindowNotSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Mapinfo kan onderstaand bestand niet registreren {1} {0} {1} Sluit of corrigeer het bestand..
        '''</summary>
        Friend Shared ReadOnly Property CouldNotRegister() As String
            Get
                Return ResourceManager.GetString("CouldNotRegister", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Directory {0} is niet gevonden..
        '''</summary>
        Friend Shared ReadOnly Property DirectoryNotFound() As String
            Get
                Return ResourceManager.GetString("DirectoryNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bestand &quot;{0}&quot; bestaat al..
        '''</summary>
        Friend Shared ReadOnly Property FileExists() As String
            Get
                Return ResourceManager.GetString("FileExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Bestand {0} is niet gevonden..
        '''</summary>
        Friend Shared ReadOnly Property FileNotFound() As String
            Get
                Return ResourceManager.GetString("FileNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Vul de naam voor de groep in a.u.b..
        '''</summary>
        Friend Shared ReadOnly Property NameNotFilled() As String
            Get
                Return ResourceManager.GetString("NameNotFilled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Selecteer kolommen.
        '''</summary>
        Friend Shared ReadOnly Property NoColumnsSelected() As String
            Get
                Return ResourceManager.GetString("NoColumnsSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen gegevens teruggevonden in {0}..
        '''</summary>
        Friend Shared ReadOnly Property NoRecordsFound() As String
            Get
                Return ResourceManager.GetString("NoRecordsFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen tabel geselecteerd.
        '''</summary>
        Friend Shared ReadOnly Property NoTableSelected() As String
            Get
                Return ResourceManager.GetString("NoTableSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Niet ingevuld.
        '''</summary>
        Friend Shared ReadOnly Property NotFilled() As String
            Get
                Return ResourceManager.GetString("NotFilled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Ongeldige waarde voor argument &apos;{0}&apos;: .
        '''</summary>
        Friend Shared ReadOnly Property NoValidArgumentValue() As String
            Get
                Return ResourceManager.GetString("NoValidArgumentValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen geldige kolom geselecteerd.
        '''</summary>
        Friend Shared ReadOnly Property NoValidColumn() As String
            Get
                Return ResourceManager.GetString("NoValidColumn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen geldige tabel.
        '''</summary>
        Friend Shared ReadOnly Property NoValidTable() As String
            Get
                Return ResourceManager.GetString("NoValidTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Geen geldige mapinfo tabelnaam..
        '''</summary>
        Friend Shared ReadOnly Property NoValidTableName() As String
            Get
                Return ResourceManager.GetString("NoValidTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Directory of bestand {0} is niet gevonden..
        '''</summary>
        Friend Shared ReadOnly Property PathNotFound() As String
            Get
                Return ResourceManager.GetString("PathNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Selecteer 1 buffer.
        '''</summary>
        Friend Shared ReadOnly Property SelectOnlyOne() As String
            Get
                Return ResourceManager.GetString("SelectOnlyOne", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Gelieve een tabel of resultaat te selecteren..
        '''</summary>
        Friend Shared ReadOnly Property SelectTabelOrResult() As String
            Get
                Return ResourceManager.GetString("SelectTabelOrResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Null reference en de lege string zijn geen geldige waarde voor method argument &quot;{0}&quot;..
        '''</summary>
        Friend Shared ReadOnly Property StringArgumentNullOrEmpty() As String
            Get
                Return ResourceManager.GetString("StringArgumentNullOrEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Kon cel waarde niet converteren van tekst type naar tijd. Waarde: {0}, Record (te tellen van 0): {1}, foutcode: {2}.
        '''</summary>
        Friend Shared ReadOnly Property TimeConvertError() As String
            Get
                Return ResourceManager.GetString("TimeConvertError", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
